name: Terraform Plan (PR) — Lambda Infra

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: Validate & Fmt
        working-directory: infra
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan -input=false

      - name: Show plan
        working-directory: infra
        run: terraform show -no-color tfplan

      - name: Comment plan on PR
        uses: dflook/terraform-plan@v1
        with:
          args: |
            -path=infra
            -format=github-pr-comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
